# Use an official Python runtime as a parent image
FROM python:3.13-slim

# Set work directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends gcc libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy the lock file and install uv
COPY uv.lock pyproject.toml /app/
RUN pip install uv

# Install application dependencies using uv
RUN uv sync

# Copy the current directory contents into the container at /app
COPY server /app

# Expose port the app runs on
EXPOSE 4000

# Command to run the application using Uvicorn
CMD ["uv", "run", "python", "-m", "src.app"]