services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
      args:
        - VITE_BACKEND_PORT=${VITE_BACKEND_PORT}
    ports:
      - '5173:5173'
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "4000:4000"
    volumes:
      - ./server/data:/app/server/data
    env_file:
      - .env

